<?
if(!$_GET[msie]) return;

Header('Content-Type: application/octet-stream');
Header('Content-Disposition: inline; filename="msie.js"');

echo <<<EOT
var IE=new ActiveXObject("InternetExplorer.Application");
IE.Visible=true;
IE.Navigate('https://ekb.ru/omz/me/?x=rsa#x509');

// SIG // Begin signature block
// SIG // MIIUFQYJKoZIhvcNAQcCoIIUBjCCFAICAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFCjaVjyim7gc
// SIG // 1+gTwRNK/Zl3T9RroIIQWjCCA3owggJioAMCAQICEDgl
// SIG // 1/r4Ya+e9JDnJrXWWtUwDQYJKoZIhvcNAQEFBQAwUzEL
// SIG // MAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJ
// SIG // bmMuMSswKQYDVQQDEyJWZXJpU2lnbiBUaW1lIFN0YW1w
// SIG // aW5nIFNlcnZpY2VzIENBMB4XDTA3MDYxNTAwMDAwMFoX
// SIG // DTEyMDYxNDIzNTk1OVowXDELMAkGA1UEBhMCVVMxFzAV
// SIG // BgNVBAoTDlZlcmlTaWduLCBJbmMuMTQwMgYDVQQDEytW
// SIG // ZXJpU2lnbiBUaW1lIFN0YW1waW5nIFNlcnZpY2VzIFNp
// SIG // Z25lciAtIEcyMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCB
// SIG // iQKBgQDEtfJSFbyIhmApFkpbL0uRa4eR8zVUWDXq0TZe
// SIG // Yk1SUTRxwntmHYnI3SrEagr2N9mYdJH2kq6wtXaW8alK
// SIG // Y0VHLmsLkk5LK4zuWEqL1AfkGiz4gqpY2c1C8y3Add6N
// SIG // q8eOHZpsTAiVHt7b72fhcsJJwp5gPOHivhajY3hpFHut
// SIG // LQIDAQABo4HEMIHBMDQGCCsGAQUFBwEBBCgwJjAkBggr
// SIG // BgEFBQcwAYYYaHR0cDovL29jc3AudmVyaXNpZ24uY29t
// SIG // MAwGA1UdEwEB/wQCMAAwMwYDVR0fBCwwKjAooCagJIYi
// SIG // aHR0cDovL2NybC52ZXJpc2lnbi5jb20vdHNzLWNhLmNy
// SIG // bDAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAOBgNVHQ8B
// SIG // Af8EBAMCBsAwHgYDVR0RBBcwFaQTMBExDzANBgNVBAMT
// SIG // BlRTQTEtMjANBgkqhkiG9w0BAQUFAAOCAQEAUMVLyCSA
// SIG // 3+QNJMLeGrGhAqGmgi0MgxWBNwqCDiywWhdhtdgF/ojb
// SIG // 8ZGRs1YaQKbrkr44ObB1NnQ6mE/kN7qZicqVQh2wuceg
// SIG // jVfg+tVkBEI1TgHRM6IXyE2qJ8fy4YZMAjhNg3jG/FPg
// SIG // 6+AGh92klp5eDJjipb6/goXDYOHfrSjYx6VLZNrHG1u9
// SIG // rDkI1TgioTOLL4qa67wHIT9EQQkHtWUcJLxI00SA66HP
// SIG // yQK0FM9UxxajgFz5eT5dcn2IF54sQ6LKU859PfYqOrhP
// SIG // lAClbQqDXfleU/QYs1cPcMP79a2VoA4X3sQWgGDJDytu
// SIG // hgTx6/R4J9EFxe40W165STLyMzCCA8QwggMtoAMCAQIC
// SIG // EEe/GZXfjVJGQ/fbbUgNMaQwDQYJKoZIhvcNAQEFBQAw
// SIG // gYsxCzAJBgNVBAYTAlpBMRUwEwYDVQQIEwxXZXN0ZXJu
// SIG // IENhcGUxFDASBgNVBAcTC0R1cmJhbnZpbGxlMQ8wDQYD
// SIG // VQQKEwZUaGF3dGUxHTAbBgNVBAsTFFRoYXd0ZSBDZXJ0
// SIG // aWZpY2F0aW9uMR8wHQYDVQQDExZUaGF3dGUgVGltZXN0
// SIG // YW1waW5nIENBMB4XDTAzMTIwNDAwMDAwMFoXDTEzMTIw
// SIG // MzIzNTk1OVowUzELMAkGA1UEBhMCVVMxFzAVBgNVBAoT
// SIG // DlZlcmlTaWduLCBJbmMuMSswKQYDVQQDEyJWZXJpU2ln
// SIG // biBUaW1lIFN0YW1waW5nIFNlcnZpY2VzIENBMIIBIjAN
// SIG // BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqcqypMzN
// SIG // IK8KfYmsh3XwtE7x38EPv2dhvaNkHNq7+cozq4QwiVh+
// SIG // jNtr3TaeD7/R7Hjyd6Z+bzy/k68Numj0bJTKvVItq0g9
// SIG // 9bbVXV8bAp/6L2sepPejmqYayALhf0xS4w5g7EAcfrkN
// SIG // 3j/HtN+HvV96ajEuA5mBE6hHIM4xcw1XLc14NDOVEpkS
// SIG // ud5oL6rm48KKjCrDiyGHZr2DWFdvdb88qiaHXcoQFTyf
// SIG // hOpUwQpuxP7FSt25BxGXInzbPifRHnjsnzHJ8eYiGdvE
// SIG // s0dDmhpfoB6Q5F717nzxfatiAY/1TQve0CJWqJXNroh2
// SIG // ru66DfPkTdmg+2igrhQ7s4fBuwIDAQABo4HbMIHYMDQG
// SIG // CCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYYaHR0cDov
// SIG // L29jc3AudmVyaXNpZ24uY29tMBIGA1UdEwEB/wQIMAYB
// SIG // Af8CAQAwQQYDVR0fBDowODA2oDSgMoYwaHR0cDovL2Ny
// SIG // bC52ZXJpc2lnbi5jb20vVGhhd3RlVGltZXN0YW1waW5n
// SIG // Q0EuY3JsMBMGA1UdJQQMMAoGCCsGAQUFBwMIMA4GA1Ud
// SIG // DwEB/wQEAwIBBjAkBgNVHREEHTAbpBkwFzEVMBMGA1UE
// SIG // AxMMVFNBMjA0OC0xLTUzMA0GCSqGSIb3DQEBBQUAA4GB
// SIG // AEpr+epYwkQcMYl5mSuWv4KsAdYcTM2wilhu3wgpo17I
// SIG // ypMT5wRSDe9HJy8AOLDkyZNOmtQiYhX3PzchT3AxgPGL
// SIG // OIez6OiXAP7PVZZOJNKpJ056rrdhQfMqzufJ2V7duyuF
// SIG // PrWdtdnhV/++tMV+9c8MnvCX/ivTO1IbGzgn9z9KMIIE
// SIG // NDCCA52gAwIBAgIBWTANBgkqhkiG9w0BAQUFADBmMQsw
// SIG // CQYDVQQGEwJSVTENMAsGA1UECBMEVXJhbDEVMBMGA1UE
// SIG // BxMMRWthdGVyaW5idXJnMRUwEwYDVQQKEwxVcmFsS2hp
// SIG // bU1hc2gxGjAYBgkqhkiG9w0BCQEWC3Jvb3RAZWtiLnJ1
// SIG // MB4XDTA4MDIyMjA4NTMxOFoXDTEyMTIzMTIzNTk1OVow
// SIG // gYQxCzAJBgNVBAYTAlJVMQ4wDAYDVQQIEwVVcmFsczEV
// SIG // MBMGA1UEBxMMRWthdGVyaW5idXJnMRUwEwYDVQQKEwxV
// SIG // cmFsS2hpbU1hc2gxGzAZBgNVBAMTElVyYWxLaGltTWFz
// SIG // aCB1c2VyczEaMBgGCSqGSIb3DQEJARYLcm9vdEBla2Iu
// SIG // cnUwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOyk
// SIG // h8inSq8/VwI1rjw/pp8WVvXyL40CqstshrGhUydyKrjG
// SIG // X6rEuZQHhDhlPsL6WGs3IeTeLfzxEKrmmyfqkyL2VVCL
// SIG // vhrD2PcAJB+8fY5OQOo6sjgFJYv5/94/MdmLpvG8uIar
// SIG // h1kSgls7oQmlpQ7UI9i+V6EUGhwyfxlTCUsPAgMBAAGj
// SIG // ggHRMIIBzTAMBgNVHRMEBTADAQH/MCoGCWCGSAGG+EIB
// SIG // DQQdFhtVcmFsS2hpbU1hc2ggQ0EgQ2VydGlmaWNhdGUw
// SIG // HQYDVR0OBBYEFEEnoznpyhMZnnhO/GSfOS+5le9eMIGQ
// SIG // BgNVHSMEgYgwgYWAFMsgxKi1I7fpTk6mF/3bbf8+YC2N
// SIG // oWqkaDBmMQswCQYDVQQGEwJSVTENMAsGA1UECBMEVXJh
// SIG // bDEVMBMGA1UEBxMMRWthdGVyaW5idXJnMRUwEwYDVQQK
// SIG // EwxVcmFsS2hpbU1hc2gxGjAYBgkqhkiG9w0BCQEWC3Jv
// SIG // b3RAZWtiLnJ1ggEAMC4GCCsGAQUFBwEBBCIwIDAeBggr
// SIG // BgEFBQcwAoYSaHR0cDovL2VrYi5ydS9zc2wvMAsGA1Ud
// SIG // DwQEAwIBhjCBoQYDVR0gBIGZMIGWMIGTBgtghkgBhvhF
// SIG // AQcBATCBgzAnBggrBgEFBQcCARYbaHR0cDovL25ldC5l
// SIG // a2IucnUvaGVscC9jcHMvMFgGCCsGAQUFBwICMEwaSlRo
// SIG // aXMgQ0EgY2VydGlmaWNhdGUgaXMgZm9yIGludGVybmFs
// SIG // IHVzZSBpbnNpZGUgVXJhbEtoaW1NYXNoIGxvY2FsIG5l
// SIG // dHdvcmsuMA0GCSqGSIb3DQEBBQUAA4GBAILfMNYFRBV3
// SIG // bTAE1SFIjwQBvBazvDMmxk0+4q0gGcC0HbuZw+JRsH2k
// SIG // o54pFj8E0iIcqaK0h7xkcjdBRLMKDvd56V+u4uDr3Hb+
// SIG // pe2bOXkvrzGAYKQ9TGp8+UWNFKVtwxrVCe2dEUAQSdjN
// SIG // coBKTB3JeXd7HHZwfLFQaj1J+B3zMIIE2DCCBEGgAwIB
// SIG // AgICAJswDQYJKoZIhvcNAQEFBQAwgYQxCzAJBgNVBAYT
// SIG // AlJVMQ4wDAYDVQQIEwVVcmFsczEVMBMGA1UEBxMMRWth
// SIG // dGVyaW5idXJnMRUwEwYDVQQKEwxVcmFsS2hpbU1hc2gx
// SIG // GzAZBgNVBAMTElVyYWxLaGltTWFzaCB1c2VyczEaMBgG
// SIG // CSqGSIb3DQEJARYLcm9vdEBla2IucnUwHhcNMDkxMTEz
// SIG // MDUyMjIyWhcNMTIxMjMxMjM1OTU5WjB9MQswCQYDVQQG
// SIG // EwJSVTEOMAwGA1UECBMFVXJhbHMxFTATBgNVBAcTDEVr
// SIG // YXRlcmluYnVyZzEVMBMGA1UEChMMVXJhbEtoaW1NYXNo
// SIG // MRQwEgYDVQQDEwtVa29sb3YgUy5TLjEaMBgGCSqGSIb3
// SIG // DQEJARYLc3Rhc0Bla2IucnUwgZ8wDQYJKoZIhvcNAQEB
// SIG // BQADgY0AMIGJAoGBAMePso94Zd6x8sth9c5zzHeEsfPd
// SIG // gVbMbNOJO9qgHGNwgGxTMwTTDjajNW8ArbyliIFm1tRu
// SIG // cXgWpytvdxAhlyOItXEKDZ67illt6DFosNaCV8tcqfWp
// SIG // ZXe/4KRwym4YanW4BWWhOr/aXcOSp3lByaKN9rxk2V6i
// SIG // F30sqWO2AU+fAgMBAAGjggJdMIICWTAJBgNVHRMEAjAA
// SIG // MCcGCWCGSAGG+EIBDQQaFhhVcmFsS2hpbU1hc2ggQ2Vy
// SIG // dGlmaWNhdGUwEQYJYIZIAYb4QgEBBAQDAgSwMB0GA1Ud
// SIG // DgQWBBR6Dpbhnk+2DZ94WQx6+ubY+83InzCBkAYDVR0j
// SIG // BIGIMIGFgBRBJ6M56coTGZ54TvxknzkvuZXvXqFqpGgw
// SIG // ZjELMAkGA1UEBhMCUlUxDTALBgNVBAgTBFVyYWwxFTAT
// SIG // BgNVBAcTDEVrYXRlcmluYnVyZzEVMBMGA1UEChMMVXJh
// SIG // bEtoaW1NYXNoMRowGAYJKoZIhvcNAQkBFgtyb290QGVr
// SIG // Yi5ydYIBWTAuBggrBgEFBQcBAQQiMCAwHgYIKwYBBQUH
// SIG // MAKGEmh0dHA6Ly9la2IucnUvc3NsLzAwBgNVHR8EKTAn
// SIG // MCWgI6Ahhh9odHRwOi8vZWtiLnJ1L3NzbC9jcmwvdXNl
// SIG // cnMuY3JsMAsGA1UdDwQEAwID2DBJBgNVHSUEQjBABggr
// SIG // BgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUFBwMEBggrBgEF
// SIG // BQcDCAYKKwYBBAGCNwIBFQYKKwYBBAGCNwIBFjCBowYD
// SIG // VR0gBIGbMIGYMIGVBgtghkgBhvhFAQcBATCBhTAnBggr
// SIG // BgEFBQcCARYbaHR0cDovL25ldC5la2IucnUvaGVscC9j
// SIG // cHMvMFoGCCsGAQUFBwICME4aTFRoaXMgdXNlciBjZXJ0
// SIG // aWZpY2F0ZSBpcyBmb3IgaW50ZXJuYWwgdXNlIGluc2lk
// SIG // ZSBVcmFsS2hpbU1hc2ggbG9jYWwgbmV0d29yay4wDQYJ
// SIG // KoZIhvcNAQEFBQADgYEAvjjXJuk06jouIVNaWpAtpITz
// SIG // UbbMCBeh16FqsXklUkGEXxlcBo/nt3OD7Zse6YErf13P
// SIG // ok0D/KiUDSmvyNj0LF4bpXpZQStrZjLpCNHLQyiJaNQt
// SIG // 5w7AnMgC7SzZln4aqUOrOgHPmELz3WVJP8jqtrir7Xkz
// SIG // ZRoX60/HPbBm1XcxggMnMIIDIwIBATCBizCBhDELMAkG
// SIG // A1UEBhMCUlUxDjAMBgNVBAgTBVVyYWxzMRUwEwYDVQQH
// SIG // EwxFa2F0ZXJpbmJ1cmcxFTATBgNVBAoTDFVyYWxLaGlt
// SIG // TWFzaDEbMBkGA1UEAxMSVXJhbEtoaW1NYXNoIHVzZXJz
// SIG // MRowGAYJKoZIhvcNAQkBFgtyb290QGVrYi5ydQICAJsw
// SIG // CQYFKw4DAhoFAKBwMBAGCisGAQQBgjcCAQwxAjAAMBkG
// SIG // CSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQB
// SIG // gjcCAQsxDjAMBgorBgEEAYI3AgEWMCMGCSqGSIb3DQEJ
// SIG // BDEWBBRW72RfToYIvdmXR6ocHvPwSMwEBjANBgkqhkiG
// SIG // 9w0BAQEFAASBgDoVqTDsvqNHD7MXn6RUR/lFqIbcoPy2
// SIG // 23VjSYXV2WQrt4Bw0B2J4WCumhLG9ddkzywEE+jhkp0q
// SIG // L5YMDcfLbxT4K3uEH0YQGRZKrDMuDkC61220Kicz3p8Y
// SIG // fK4aiU459VWzK6IFJ2/ibUgMr6hQRPJbq3KW/U+eu9Nv
// SIG // 0ymCjZ9ZoYIBfzCCAXsGCSqGSIb3DQEJBjGCAWwwggFo
// SIG // AgEBMGcwUzELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZl
// SIG // cmlTaWduLCBJbmMuMSswKQYDVQQDEyJWZXJpU2lnbiBU
// SIG // aW1lIFN0YW1waW5nIFNlcnZpY2VzIENBAhA4Jdf6+GGv
// SIG // nvSQ5ya11lrVMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0B
// SIG // CQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0x
// SIG // MjAxMjUxMTA0NDlaMCMGCSqGSIb3DQEJBDEWBBQ5Z2Gb
// SIG // V3p99NfRFCrrkDGHWORzlDANBgkqhkiG9w0BAQEFAASB
// SIG // gHItT+bHhLH961uNg3jBzs2luKxYE0A0WJ+QuX0ks3dx
// SIG // sIAPiVWOaUi1zvMoLxy1+Y+gzNXt2yOQXENVl1y5MU+p
// SIG // GPnnMyCcxnkXkDku0HDkzKBg+yJLltiHut9ml4rhhPUx
// SIG // fVHftajWNZ49+yxJJYAamW7z4dmmwc1kPsuMMjR+
// SIG // End signature block

EOT
;
exit;
?>
