<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.10.0.2 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 9697 2006-11-13 08:32:28Z nijel $
 * Date: Thu, 15 Mar 2007 12:03:24 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (cookie) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'cookie';

/* End of servers configuration */

$cfg['blowfish_secret'] = '45f935edce3357.54161461';
$cfg['AllowAnywhereRecoding'] = false;
$cfg['DefaultCharset'] = 'windows-1251';
$cfg['RecodingEngine'] = 'iconv';
$cfg['IconvExtraParams'] = '//TRANSLIT';
?>
